"""BUDDY Interaction Models and Action Proposals.

Defines strongly typed action representations, target bindings, mouse buttons,
keyboard restrictions, and UIActionProposal structures.
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from app.tools.models import ToolRequest, ToolRiskLevel
from app.vision.models import BoundingBox, VisionTarget


class MouseButton(str, Enum):
    """Allowed physical mouse buttons."""

    LEFT = "left"
    RIGHT = "right"
    MIDDLE = "middle"


class InteractionAction(str, Enum):
    """Permitted UI interaction operations."""

    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    SCROLL = "scroll"
    MOVE = "move"
    TYPE = "type"
    KEY_PRESS = "key_press"


class TextSensitivity(str, Enum):
    """Security classification of text intended for typing."""

    NORMAL_TEXT = "normal_text"
    SENSITIVE_TEXT = "sensitive_text"


# Allowlisted non-alphanumeric keyboard keys
ALLOWED_KEYS: set[str] = {
    "ENTER", "ESC", "TAB", "BACKSPACE", "SPACE",
    "ARROW_UP", "ARROW_DOWN", "ARROW_LEFT", "ARROW_RIGHT",
    "HOME", "END", "PAGE_UP", "PAGE_DOWN",
}


class InteractionRequest(BaseModel):
    """Validated and bound instruction to execute a specific UI operation."""

    request_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    action_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    action_type: InteractionAction
    target_id: Optional[str] = Field(default=None, description="Must reference an empirically verified VisionTarget")
    bounding_box: Optional[Tuple[int, int, int, int]] = Field(default=None, description="(x, y, w, h)")
    screen_id: str = Field(default="primary")
    coordinates: Optional[Tuple[float, float]] = Field(default=None, description="(x, y) target coordinates")
    text: Optional[str] = Field(default=None, description="Text string to type")
    key: Optional[str] = Field(default=None, description="Allowlisted keyboard key name")
    amount: Optional[int] = Field(default=None, description="Scroll delta lines")
    conversation_id: Optional[str] = None
    screen_fingerprint: Optional[str] = Field(default=None, description="Fingerprint of screen when target was identified")
    screen_dimensions: Optional[Tuple[int, int]] = Field(default=None, description="(width, height)")
    timestamp: float = Field(default_factory=time.time)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {"extra": "forbid"}

    def to_tool_request(self) -> ToolRequest:
        """Translate this InteractionRequest into an executable ToolRequest for ToolExecutor."""
        args: Dict[str, Any] = {}
        tool_name = ""

        if self.action_type == InteractionAction.CLICK:
            tool_name = "mouse.click"
            args = {
                "target_id": self.target_id,
                "screen_fingerprint": self.screen_fingerprint,
            }
        elif self.action_type == InteractionAction.DOUBLE_CLICK:
            tool_name = "mouse.double_click"
            args = {
                "target_id": self.target_id,
                "screen_fingerprint": self.screen_fingerprint,
            }
        elif self.action_type == InteractionAction.SCROLL:
            tool_name = "mouse.scroll"
            args = {"amount": self.amount or 0}
        elif self.action_type == InteractionAction.KEY_PRESS:
            tool_name = "keyboard.key_press"
            args = {"key": self.key}
        elif self.action_type == InteractionAction.TYPE:
            tool_name = "keyboard.type_text"
            args = {"text": self.text or ""}
        else:
            raise ValueError(f"Action '{self.action_type}' cannot be converted to a tool invocation.")

        return ToolRequest(
            request_id=self.request_id,
            tool_name=tool_name,
            arguments=args,
            conversation_id=self.conversation_id,
        )


class UIActionProposal(BaseModel):
    """Proposal generated by AI or Planner linking intent to a verified VisionTarget."""

    action_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    action_type: InteractionAction
    target: VisionTarget
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    screen_fingerprint: str
    screen_dimensions: Tuple[int, int]
    risk_level: ToolRiskLevel = Field(default=ToolRiskLevel.MODERATE)
    reason: Optional[str] = None
    text: Optional[str] = None
    key: Optional[str] = None
    amount: Optional[int] = None

    model_config = {"frozen": True}

    def to_interaction_request(self, conversation_id: Optional[str] = None) -> InteractionRequest:
        """Convert a validated UIActionProposal into a bound InteractionRequest."""
        cx, cy = self.target.center
        return InteractionRequest(
            action_id=self.action_id,
            action_type=self.action_type,
            target_id=self.target.target_id,
            bounding_box=self.target.bounding_box.as_tuple,
            coordinates=(float(cx), float(cy)),
            screen_fingerprint=self.screen_fingerprint,
            screen_dimensions=self.screen_dimensions,
            text=self.text,
            key=self.key,
            amount=self.amount,
            conversation_id=conversation_id,
            metadata={"label": self.target.label, "category": self.target.category},
        )

    def to_tool_request(self, conversation_id: Optional[str] = None) -> ToolRequest:
        """Convert UIActionProposal directly into an executable ToolRequest for ToolExecutor."""
        return self.to_interaction_request(conversation_id=conversation_id).to_tool_request()
